# Generated by Django 2.1.2 on 2018-10-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_code', models.CharField(choices=[('1', 'תקן איוש ונלוות'), ('2', 'פעילות'), ('3', 'חווית המטופל'), ('4', 'הון אנושי'), ('5', 'איכות ובטיחות'), ('6', 'תשתית כלכלית ופזית'), ('7', 'ניצולת חדרי ניתוח'), ('8', 'תשתית טכנולוגית')], max_length=1)),
                ('measure_code', models.IntegerField(choices=[('1', 'ON TARGET'), ('2', 'LOW IS BETTER'), ('3', 'HIGH IS BETTER')], verbose_name='Measure_Code')),
                ('measure_name', models.CharField(max_length=64, verbose_name='Measure_Name')),
                ('measure_desc', models.TextField(max_length=200, verbose_name='Measure_Desc')),
                ('criteria_inclusion', models.CharField(max_length=72, verbose_name='Criteria_Inclusion')),
                ('removal_criteria', models.CharField(max_length=72, verbose_name='Removal_Criteria')),
                ('numerator', models.CharField(max_length=64, verbose_name='Numerator')),
                ('denominator', models.CharField(max_length=64, verbose_name='denominator')),
                ('hospital_type', models.CharField(choices=[('1', 'כללים'), ('2', 'גריאטריים'), ('3', 'פסיכיאטריים')], max_length=1)),
                ('measure_type', models.CharField(choices=[('1', 'ON TARGET'), ('2', 'LOW IS BETTER'), ('3', 'HIGH IS BETTER')], max_length=64, verbose_name='Measure_Type')),
                ('measuring_frequency', models.CharField(choices=[('1', 'יומי'), ('2', 'חודשי'), ('3', 'רבעוני'), ('4', 'חציוני'), ('5', 'שנתי')], max_length=64, verbose_name='Measuring_Frequency')),
                ('unit_measure', models.CharField(max_length=64, verbose_name='Unit_Measure')),
                ('digit_num', models.IntegerField(verbose_name='Num_Of_Digits')),
                ('separate_thousands', models.BooleanField(max_length=1, verbose_name='Separate_Thousands')),
                ('active', models.CharField(choices=[('1', 'פעיל'), ('2', 'לא פעיל')], max_length=1, verbose_name='Active')),
                ('from_date', models.DateTimeField(verbose_name='From_Date')),
                ('to_date', models.DateTimeField(verbose_name='To_Date')),
                ('target', models.CharField(max_length=64, verbose_name='Target')),
                ('remarks', models.TextField(max_length=484, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(unique=True, verbose_name='Version_No')),
                ('version_name', models.CharField(max_length=72, verbose_name='Version_Name')),
                ('version_type', models.CharField(choices=[('1', 'יומי'), ('2', 'חודשי'), ('3', 'רבעוני'), ('4', 'חציוני'), ('5', 'שנתי')], max_length=1, verbose_name='Version_Type')),
                ('hospital_type', models.CharField(choices=[('1', 'כללים'), ('2', 'גריאטריים'), ('3', 'פסיכיאטריים')], max_length=1, verbose_name='Hospital_Type')),
                ('active', models.CharField(choices=[('1', 'פעיל'), ('2', 'לא פעיל')], max_length=1, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_At')),
                ('updated_at', models.DateTimeField(verbose_name='Update_At')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='version',
            field=models.ManyToManyField(to='app_data.Version'),
        ),
    ]
