# Generated by Django 2.1.2 on 2018-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='measure',
            field=models.ManyToManyField(to='app_data.Measure'),
        ),
    ]
