# Generated by Django 2.1.2 on 2018-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_auto_20181023_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure_code',
            field=models.IntegerField(choices=[(1, 'ON TARGET'), ('2', 'LOW IS BETTER'), ('3', 'HIGH IS BETTER')], verbose_name='Measure_Code'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure_type',
            field=models.CharField(choices=[(1, 'ON TARGET'), ('2', 'LOW IS BETTER'), ('3', 'HIGH IS BETTER')], max_length=64, verbose_name='Measure_Type'),
        ),
    ]
