# Generated by Django 2.1.2 on 2018-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_auto_20181023_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure_code',
            field=models.CharField(max_length=32, verbose_name='Measure_Code'),
        ),
    ]
