# Generated by Django 2.1.2 on 2018-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_auto_20181023_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='active',
            field=models.BooleanField(choices=[(1, 'פעיל'), (2, 'לא פעיל')], max_length=1, verbose_name='Active'),
        ),
    ]
