# Generated by Django 2.1.2 on 2018-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_auto_20181023_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='active',
            field=models.BooleanField(choices=[('1', 'פעיל'), ('2', 'לא פעיל')], max_length=1, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='remarks',
            field=models.TextField(blank=True, max_length=484, null=True, verbose_name='Remarks'),
        ),
    ]
