# Generated by Django 2.1.2 on 2018-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_auto_20181111_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='version',
            name='cancel',
        ),
        migrations.AlterField(
            model_name='version',
            name='create_date',
            field=models.DateField(),
        ),
    ]
