# Generated by Django 2.1.2 on 2018-11-07 09:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1000)),
                ('measure_code', models.CharField(max_length=32)),
                ('hospital_type', models.CharField(max_length=1)),
                ('hospital_code', models.CharField(max_length=6)),
                ('measure_value', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=28)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=28)),
                ('cancel', models.BooleanField(max_length=1)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_user', models.CharField(blank=True, max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='DecryptionTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('values_list', djongo.models.fields.ListField()),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_code', models.CharField(max_length=32)),
                ('hospital_type', models.CharField(max_length=1)),
                ('measure_name', models.CharField(max_length=64)),
                ('measure_desc', models.TextField(max_length=200)),
                ('business_topic', models.CharField(max_length=24)),
                ('criteria_inclusion', models.CharField(max_length=72)),
                ('removal_criteria', models.CharField(max_length=72)),
                ('numerator', models.CharField(max_length=64)),
                ('denominator', models.CharField(max_length=64)),
                ('measure_type', models.CharField(max_length=64)),
                ('measuring_frequency', models.CharField(max_length=64)),
                ('measure_unit', models.IntegerField()),
                ('digit_num', models.IntegerField()),
                ('separate_thousands', models.BooleanField(max_length=1)),
                ('active', models.CharField(max_length=1)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('target_default', models.FloatField(default=100)),
                ('remarks', models.TextField(blank=True, max_length=484)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=28)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=28)),
                ('cancel', models.BooleanField(max_length=1)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_user', models.CharField(blank=True, max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1000)),
                ('hospital_type', models.CharField(max_length=1)),
                ('version_name', models.CharField(max_length=72)),
                ('version_type', models.CharField(max_length=1)),
                ('version_desc', models.CharField(max_length=121)),
                ('active', models.CharField(max_length=1)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=28)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=28)),
                ('cancel', models.BooleanField(max_length=1)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_user', models.CharField(blank=True, max_length=28)),
                ('measure', djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='app_data.Measure')),
            ],
        ),
    ]
