# Generated by Django 2.1.2 on 2018-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_auto_20181111_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
