# Generated by Django 2.1.2 on 2018-11-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_auto_20181111_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualexecution',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualexecution',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualexecution',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='measure',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
